/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Calculator;

/**
 *
 * @author micojasmin
 */
public class Calc extends javax.swing.JFrame {

    String display,total,operations;
    double firstnum,secondnum, result1,result2,result3,result4, thirdnum,result;
 

    public Calc() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bttn7 = new javax.swing.JButton();
        bttn8 = new javax.swing.JButton();
        bttn9 = new javax.swing.JButton();
        bttn4 = new javax.swing.JButton();
        bttn5 = new javax.swing.JButton();
        bttn6 = new javax.swing.JButton();
        bttn1 = new javax.swing.JButton();
        bttn2 = new javax.swing.JButton();
        btnn3 = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jButtonAdd = new javax.swing.JButton();
        jButtonMulti = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jButtonSubtract = new javax.swing.JButton();
        bttn0 = new javax.swing.JButton();
        jButtonEquals = new javax.swing.JButton();
        jButtonChange = new javax.swing.JButton();
        jbttnDelete = new javax.swing.JButton();
        jButtonDot = new javax.swing.JButton();
        jButtonPercentage = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextFieldDisplay = new javax.swing.JTextField();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        bttn7.setBackground(new java.awt.Color(51, 51, 51));
        bttn7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bttn7.setForeground(new java.awt.Color(255, 255, 255));
        bttn7.setText("7");
        bttn7.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, new java.awt.Color(204, 204, 204)));
        bttn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn7ActionPerformed(evt);
            }
        });
        jPanel1.add(bttn7);
        bttn7.setBounds(20, 150, 55, 40);

        bttn8.setBackground(new java.awt.Color(51, 51, 51));
        bttn8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bttn8.setForeground(new java.awt.Color(204, 204, 204));
        bttn8.setText("8");
        bttn8.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, java.awt.Color.lightGray));
        bttn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn8ActionPerformed(evt);
            }
        });
        jPanel1.add(bttn8);
        bttn8.setBounds(80, 150, 55, 40);

        bttn9.setBackground(new java.awt.Color(51, 51, 51));
        bttn9.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bttn9.setForeground(new java.awt.Color(204, 204, 204));
        bttn9.setText("9");
        bttn9.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray));
        bttn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn9ActionPerformed(evt);
            }
        });
        jPanel1.add(bttn9);
        bttn9.setBounds(140, 150, 55, 40);

        bttn4.setBackground(new java.awt.Color(51, 51, 51));
        bttn4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bttn4.setForeground(new java.awt.Color(204, 204, 204));
        bttn4.setText("4");
        bttn4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray));
        bttn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn4ActionPerformed(evt);
            }
        });
        jPanel1.add(bttn4);
        bttn4.setBounds(20, 200, 55, 40);

        bttn5.setBackground(new java.awt.Color(51, 51, 51));
        bttn5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bttn5.setForeground(new java.awt.Color(204, 204, 204));
        bttn5.setText("5");
        bttn5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray));
        bttn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn5ActionPerformed(evt);
            }
        });
        jPanel1.add(bttn5);
        bttn5.setBounds(80, 200, 55, 40);

        bttn6.setBackground(new java.awt.Color(51, 51, 51));
        bttn6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bttn6.setForeground(new java.awt.Color(204, 204, 204));
        bttn6.setText("6");
        bttn6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray));
        bttn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn6ActionPerformed(evt);
            }
        });
        jPanel1.add(bttn6);
        bttn6.setBounds(140, 200, 55, 40);

        bttn1.setBackground(new java.awt.Color(51, 51, 51));
        bttn1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bttn1.setForeground(new java.awt.Color(204, 204, 204));
        bttn1.setText("1");
        bttn1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray));
        bttn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn1ActionPerformed(evt);
            }
        });
        jPanel1.add(bttn1);
        bttn1.setBounds(20, 250, 55, 40);

        bttn2.setBackground(new java.awt.Color(51, 51, 51));
        bttn2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bttn2.setForeground(new java.awt.Color(204, 204, 204));
        bttn2.setText("2");
        bttn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray));
        bttn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn2ActionPerformed(evt);
            }
        });
        jPanel1.add(bttn2);
        bttn2.setBounds(80, 250, 55, 40);

        btnn3.setBackground(new java.awt.Color(51, 51, 51));
        btnn3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        btnn3.setForeground(new java.awt.Color(204, 204, 204));
        btnn3.setText("3");
        btnn3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray));
        btnn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnn3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnn3);
        btnn3.setBounds(140, 250, 55, 40);

        jButtonDiv.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDiv.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButtonDiv.setText("/");
        jButtonDiv.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, java.awt.Color.darkGray));
        jButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDiv);
        jButtonDiv.setBounds(200, 250, 55, 40);

        jButtonAdd.setBackground(new java.awt.Color(204, 204, 204));
        jButtonAdd.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButtonAdd.setText("+");
        jButtonAdd.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, java.awt.Color.darkGray));
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonAdd);
        jButtonAdd.setBounds(200, 150, 55, 40);

        jButtonMulti.setBackground(new java.awt.Color(204, 204, 204));
        jButtonMulti.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButtonMulti.setText("x");
        jButtonMulti.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, java.awt.Color.darkGray));
        jButtonMulti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultiActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonMulti);
        jButtonMulti.setBounds(200, 300, 55, 40);

        jButtonClear.setBackground(new java.awt.Color(51, 51, 51));
        jButtonClear.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonClear.setForeground(new java.awt.Color(255, 255, 255));
        jButtonClear.setText("C");
        jButtonClear.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(204, 204, 204), null, java.awt.Color.white));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonClear);
        jButtonClear.setBounds(20, 110, 55, 30);

        jButtonSubtract.setBackground(new java.awt.Color(204, 204, 204));
        jButtonSubtract.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButtonSubtract.setText("-");
        jButtonSubtract.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, java.awt.Color.darkGray));
        jButtonSubtract.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSubtractActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonSubtract);
        jButtonSubtract.setBounds(200, 200, 55, 40);

        bttn0.setBackground(new java.awt.Color(51, 51, 51));
        bttn0.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        bttn0.setForeground(new java.awt.Color(204, 204, 204));
        bttn0.setText("0");
        bttn0.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray));
        bttn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttn0ActionPerformed(evt);
            }
        });
        jPanel1.add(bttn0);
        bttn0.setBounds(20, 300, 55, 40);

        jButtonEquals.setBackground(new java.awt.Color(204, 204, 204));
        jButtonEquals.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        jButtonEquals.setText("=");
        jButtonEquals.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, java.awt.Color.darkGray));
        jButtonEquals.setMaximumSize(new java.awt.Dimension(42, 25));
        jButtonEquals.setMinimumSize(new java.awt.Dimension(42, 25));
        jButtonEquals.setPreferredSize(new java.awt.Dimension(42, 25));
        jButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualsActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonEquals);
        jButtonEquals.setBounds(140, 300, 55, 40);

        jButtonChange.setBackground(new java.awt.Color(204, 204, 204));
        jButtonChange.setText("+/-");
        jButtonChange.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, java.awt.Color.darkGray));
        jButtonChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonChangeActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonChange);
        jButtonChange.setBounds(140, 110, 55, 30);

        jbttnDelete.setBackground(new java.awt.Color(51, 51, 51));
        jbttnDelete.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jbttnDelete.setForeground(new java.awt.Color(204, 204, 204));
        jbttnDelete.setText("DEL");
        jbttnDelete.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray));
        jbttnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbttnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(jbttnDelete);
        jbttnDelete.setBounds(80, 110, 55, 30);

        jButtonDot.setBackground(new java.awt.Color(204, 204, 204));
        jButtonDot.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jButtonDot.setText(".");
        jButtonDot.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, java.awt.Color.darkGray));
        jButtonDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDotActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonDot);
        jButtonDot.setBounds(80, 300, 55, 40);

        jButtonPercentage.setBackground(new java.awt.Color(204, 204, 204));
        jButtonPercentage.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButtonPercentage.setText("%");
        jButtonPercentage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.darkGray, null, java.awt.Color.darkGray));
        jButtonPercentage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPercentageActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonPercentage);
        jButtonPercentage.setBounds(200, 110, 55, 30);

        jButton2.setBackground(new java.awt.Color(255, 102, 102));
        jButton2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jButton2.setText("x");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(260, 10, 38, 20);

        jTextFieldDisplay.setEditable(false);
        jTextFieldDisplay.setBackground(new java.awt.Color(51, 51, 51));
        jTextFieldDisplay.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jTextFieldDisplay.setForeground(new java.awt.Color(204, 204, 204));
        jTextFieldDisplay.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jTextFieldDisplay.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.lightGray, null, java.awt.Color.lightGray));
        jTextFieldDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldDisplayActionPerformed(evt);
            }
        });
        jPanel1.add(jTextFieldDisplay);
        jTextFieldDisplay.setBounds(20, 40, 240, 50);

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background/475ae0b97efeeec4729b3de107f88918.jpg"))); // NOI18N
        jPanel1.add(Background);
        Background.setBounds(0, 0, 310, 400);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnn3ActionPerformed

        String button = jTextFieldDisplay.getText() + btnn3.getText();
        jTextFieldDisplay.setText(button);
    }//GEN-LAST:event_btnn3ActionPerformed

    private void bttn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn5ActionPerformed
        String button = jTextFieldDisplay.getText() + bttn5.getText();
        jTextFieldDisplay.setText(button);
    }//GEN-LAST:event_bttn5ActionPerformed

    private void jButtonSubtractActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSubtractActionPerformed
        // TODO add your handling code here:

        try {
            firstnum = Double.parseDouble(jTextFieldDisplay.getText());
            jTextFieldDisplay.setText("");

            operations = "-";
        } catch (NumberFormatException e) {
            jTextFieldDisplay.setText("");
        }
    }//GEN-LAST:event_jButtonSubtractActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        jTextFieldDisplay.setText("");
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void bttn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn0ActionPerformed
        if (jTextFieldDisplay.getText() == "") {
            jTextFieldDisplay.setText(bttn0.getText());
        } else {
            display = jTextFieldDisplay.getText() + bttn0.getText();
            jTextFieldDisplay.setText(display);
        }
    }//GEN-LAST:event_bttn0ActionPerformed

    private void jbttnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbttnDeleteActionPerformed
        int dis = jTextFieldDisplay.getText().length();// this get length
        if (dis > 0) { //condition
            StringBuffer b = new StringBuffer(jTextFieldDisplay.getText()); //gettext
            b.deleteCharAt((dis) - 1); // delete 1 length
           
            jTextFieldDisplay.setText(b.toString());
        }


    }//GEN-LAST:event_jbttnDeleteActionPerformed

    private void bttn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn7ActionPerformed
        String button = jTextFieldDisplay.getText() + bttn7.getText();
        jTextFieldDisplay.setText(button);
    }//GEN-LAST:event_bttn7ActionPerformed

    private void bttn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn8ActionPerformed
        String button = jTextFieldDisplay.getText() + bttn8.getText();
        jTextFieldDisplay.setText(button);
    }//GEN-LAST:event_bttn8ActionPerformed

    private void bttn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn1ActionPerformed
        String button = jTextFieldDisplay.getText() + bttn1.getText();
        jTextFieldDisplay.setText(button);
    }//GEN-LAST:event_bttn1ActionPerformed

    private void bttn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn2ActionPerformed
        String button = jTextFieldDisplay.getText() + bttn2.getText();
        jTextFieldDisplay.setText(button);
    }//GEN-LAST:event_bttn2ActionPerformed

    private void bttn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn4ActionPerformed
        String button = jTextFieldDisplay.getText() + bttn4.getText();
        jTextFieldDisplay.setText(button);
    }//GEN-LAST:event_bttn4ActionPerformed

    private void bttn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn6ActionPerformed
        String button = jTextFieldDisplay.getText() + bttn6.getText();
        jTextFieldDisplay.setText(button);
    }//GEN-LAST:event_bttn6ActionPerformed

    private void bttn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttn9ActionPerformed
        String button = jTextFieldDisplay.getText() + bttn9.getText();
        jTextFieldDisplay.setText(button);
    }//GEN-LAST:event_bttn9ActionPerformed

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // if button add already set else break
        try {
            firstnum = Double.parseDouble(jTextFieldDisplay.getText());
            jTextFieldDisplay.setText("");

            operations = "+";
        } catch (NumberFormatException e) {
            jTextFieldDisplay.setText("");
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonPercentageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPercentageActionPerformed

        try {

            firstnum = Double.parseDouble(jTextFieldDisplay.getText());
            jTextFieldDisplay.setText("");
            operations = "%";
        } catch (NumberFormatException e) {
            jTextFieldDisplay.setText("");
        }
    }//GEN-LAST:event_jButtonPercentageActionPerformed

    private void jButtonDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDotActionPerformed

        if (!jTextFieldDisplay.getText().contains(jButtonDot.getText())) {

            jTextFieldDisplay.setText(jTextFieldDisplay.getText() + jButtonDot.getText());
        }
    }//GEN-LAST:event_jButtonDotActionPerformed

    private void jButtonChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonChangeActionPerformed
        try {
            int x = Integer.parseInt(jTextFieldDisplay.getText());
            x = x * (-1);
            String con = String.format("%d", x);
            jTextFieldDisplay.setText(con);
        } catch (NumberFormatException e) {
            jTextFieldDisplay.setText("SyntaxError");
        }
    }//GEN-LAST:event_jButtonChangeActionPerformed

    private void jTextFieldDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldDisplayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldDisplayActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivActionPerformed
        // TODO add your handling code here:
        try {

            firstnum = Double.parseDouble(jTextFieldDisplay.getText());
            jTextFieldDisplay.setText("");

            operations = "/";
        } catch (NumberFormatException e) {
            jTextFieldDisplay.setText("");
        }
    }//GEN-LAST:event_jButtonDivActionPerformed

    private void jButtonMultiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultiActionPerformed
        try {
            firstnum = Double.parseDouble(jTextFieldDisplay.getText());
            jTextFieldDisplay.setText("");

            operations = "*";
        } catch (NumberFormatException e) {
            jTextFieldDisplay.setText("");
        }
    }//GEN-LAST:event_jButtonMultiActionPerformed

    private void jButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualsActionPerformed
       try {
            secondnum = Double.parseDouble(jTextFieldDisplay.getText());
            
            if (operations.equals("+")) {
                result = (firstnum + secondnum);
                jTextFieldDisplay.setText(String.format("%.2f", result));
            } else if (operations.equals("-")) {
                result = firstnum - secondnum;
                jTextFieldDisplay.setText(String.format("%.2f", result));
            } else if (operations.equals("%")) {
                result = firstnum * secondnum / 100;
                jTextFieldDisplay.setText(String.format("%.2f", result));
            } else if (operations.equals("/")) {
                result = firstnum / secondnum;
                jTextFieldDisplay.setText(String.format("%.2f", result));
            } else if (operations.equals("*")) {
                result = firstnum * secondnum;
                jTextFieldDisplay.setText(String.format("%.2f", result));
            }
        } catch (NumberFormatException e) {
            jTextFieldDisplay.setText("");
        }
       
    
     
    }//GEN-LAST:event_jButtonEqualsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton btnn3;
    private javax.swing.JButton bttn0;
    private javax.swing.JButton bttn1;
    private javax.swing.JButton bttn2;
    private javax.swing.JButton bttn4;
    private javax.swing.JButton bttn5;
    private javax.swing.JButton bttn6;
    private javax.swing.JButton bttn7;
    private javax.swing.JButton bttn8;
    private javax.swing.JButton bttn9;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonChange;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonDot;
    private javax.swing.JButton jButtonEquals;
    private javax.swing.JButton jButtonMulti;
    private javax.swing.JButton jButtonPercentage;
    private javax.swing.JButton jButtonSubtract;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldDisplay;
    private javax.swing.JButton jbttnDelete;
    // End of variables declaration//GEN-END:variables
}
